


# Permalinks
permalink:        pretty

# Setup
title:            nomisma
tagline:          'A library for working with data from nomisma.org'
description:      'Work with simple tabular representations of data for coin issues, mints and hoards freely available from nomisma.org'
baseurl: '/nomisma/'


author:
  name:           'Neel Smith'


links:
  - title: Github source
    url: https://github.com/neelsmith/nomisma
    external: true
  - title: Me on github
    url: http://neelsmith.github.io/
    external: true
